### ISSUE TITLE
Deploying an application that contains several packages

### ISSUE THREAD

**Issue by matsrietdijk** [mietek/haskell-on-heroku#44]
First: thanks for your open source work, Halcyon, HoH, Cannot, ..., they're all amazing pieces of work.

We are working on a CMS in Haskell (to be publicly announced in the coming week), that we would like to deploy with HoH (and provide a tutorial for others to deploy theirs with HoH).

The CMS recommends to break up features into separate packages, therefor a git repo of a project that uses this CMS contains a subdirectory for each package.

For instance: https://github.com/lambdacms/lambdacms.org

The "base" subfolder is contains the master site, it builds the actual binary that should be hosted. The other subdirectories contain dependencies of the "base" app.

Is it possible to install an app like this with HoH?  Or do you have suggestions on how we can make it easier for HoH to install an app like this?

Thanks.

**Comment by mietek** [comment]
Thanks for the kind words.  I’ve now opened a small PR, fixing a few minor packaging issues in your project (https://github.com/lambdacms/lambdacms.org/pull/1).

With these changes in place, I’ve successfully built your project on a regular Ubuntu 14.04 machine, then deployed it to Heroku:

```
$ curl -s https://lambdacms-dot-org.herokuapp.com | head
<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Welcome To LambdaCms-org!</title><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="http://localhost:3000/static/combined/OrNDj4Wt.css"><link rel="stylesheet" href="http://localhost:3000/static/tmp/autogen-qeZQLAVQ.css"></meta><body><nav class="navbar navbar-default navbar-static-top"><div class="container-fluid">
<div class="navbar-header"><button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#navbar"><span class="sr-only">Toggle Navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>

<div class="collapse navbar-collapse" id="navbar"><ul class="nav navbar-nav"><li class="active"><a href=http://localhost:3000/>Home</a></li>
```

In order to get here, I first split the project into three _git_ repositories, one per package:

- https://github.com/mietek/lambdacms.org-base
- https://github.com/mietek/lambdacms.org-page
- https://github.com/mietek/lambdacms.org-tutorial

Next, I added a number of Halcyon magic files to the master package (https://github.com/mietek/lambdacms.org-base/commit/185bdbd7e71c9d96b2db87ba5d93cee320138c3c:

```
$ git show --name-only HEAD
commit 185bdbd7e71c9d96b2db87ba5d93cee320138c3c
Author: Miëtek Bak <mietek@bak.io>
Date:   Thu Jan 29 16:29:25 2015 +0000

    Package with Halcyon

.halcyon/constraints
.halcyon/extra-data-files
.halcyon/extra-os-packages
.halcyon/sandbox-extra-apps
.halcyon/sandbox-extra-apps-constraints/alex-3.1.4.constraints
.halcyon/sandbox-extra-apps-constraints/happy-1.19.5.constraints
.halcyon/sandbox-extra-configure-flags
.halcyon/sandbox-extra-os-packages
.halcyon/sandbox-sources
```

Each of these files is described in the [Halcyon reference](https://halcyon.sh/reference/).  Most importantly, the [`HALCYON_SANDBOX_SOURCES`](https://halcyon.sh/reference/#halcyon_sandbox_sources) option is used to point to the other two packages:

```
$ cat .halcyon/sandbox-sources 
https://github.com/mietek/lambdacms.org-page
https://github.com/mietek/lambdacms.org-tutorial
```

Finally, I configured the app in the manner required by Yesod, by manually extracting portions of the `DATABASE_URL` set by `heroku addons:add heroku-postgresql:hobby-dev`:

```
$ heroku config | grep PG
PGDATABASE:                   d8n9…
PGHOST:                       ec2-….compute-1.amazonaws.com
PGPASS:                       IJJb…
PGUSER:                       kjrj…
```

When deploying on Heroku, Yesod automatically finds the `static` directory in the current working directory.  When deploying elsewhere, it’ll be necessary to also point `STATIC_DIR` into the Cabal run-time data files directory before starting the app.

Join `#haskell-deployment` on the [freenode](https://freenode.net) IRC network if you’d like to discuss this.

**Comment by matsrietdijk** [comment]
Thank you for this answer. I guess we will be waiting until it's possible to deploy the application from a single repository. Splitting them up into multiple repositories isn't really an option for our use case.

**Comment by matsrietdijk** [comment]
Thanks for this answer and the fixes. We are going to use this multi-repo setup for now.

**Comment by cies** [comment]
Thanks @mietek for the elaborate reply, and the PR. As @matsrietdijk said we'll move to 1-repo-per-cabal-file and include a HoH-deploy tutorial for the initial release.

I'm still interested why you think multi-repos are not ideal. I can come up with some reasons, but I also see reasons in favor of them.

**Comment by mietek** [comment]
Oops,  just noticed `APPROOT` was set incorrectly on the live instance ([lambdacms.herokuapp.com](https://lambdacms.herokuapp.com/)). Images and styles work now.

**Comment by mietek** [comment]
The multi-repo split interacts with Halcyon in a complex fashion.  It would be better to explain this in chat, once you have gone through the [Halcyon tutorial](https://halcyon.sh/tutorial/).

**Comment by cies** [comment]
Once again thanks for the resourceful reply. We'll reconsider it, in the light of the release we are planning to do in the coming days.
