### ISSUE TITLE
Support / use GHC 7.10

### ISSUE THREAD

**Issue by wereHamster** [mietek/haskell-on-heroku#54]
GHC 7.10 has been out for a while now.

**Comment by mietek** [comment]
Halcyon has supported GHC 7.10.1 since March (https://github.com/mietek/halcyon/commit/83eb6a260b286598f04dc962b534b8b9ac62c3e6), and GHC 7.10.1-rc2 since January (https://github.com/mietek/halcyon/commit/c9634862b1f3b8ff34b12d5191fc0848cf8a8d27).

Currently, the right version of GHC to use is implied by the `base` package constraint:
```
$ grep -E '^base-' .halcyon/constraints
base-4.7.0.2
```

**Comment by wereHamster** [comment]
I see. Absent any constraints it prefers 7.8 over 7.10. Is that intentional?

**Comment by mietek** [comment]
Yes. Absent any constraints, tou can override the default by setting [`HALCYON_GHC_VERSION`](https://halcyon.sh/reference/#halcyon_ghc_version):
```
$ heroku config:set HALCYON_GHC_VERSION=7.10.1
```
